base implementation
codex-team/hawk.cron-manager pull request #1
Opened 2020-04-22 22:10 UTC by nikmel2803

2020-04-23 16:19 UTC, neSpecc approved these changes

2020-04-23 16:19 UTC, neSpecc commented on src/types.ts
> +/**
better name `types.d.ts`

2020-04-23 17:22 UTC, gohabereg requested changes
Что произойдет, если процесс упадет или завершится пользователем? Джобы для крона удалятся?

И как добавить новую джобу? Обновить конфиг и перезапустить (тогда возвращаемся к первому вопросу)?

2020-04-23 17:22 UTC, gohabereg commented on src/manager.ts
> +    return this.channelWithRegistry.sendToQueue(
Тут надо через publish сделать сразу, чтобы потом не перепиливать

2020-04-23 17:22 UTC, gohabereg commented on src/manager.ts
> +        await this.addTask(task.workerType, task.payload || {});
Зачем тут async/await? Можно же просто

```
new CronJob(task.schedule, () => this.addTask(task.workerType, task.payload || {});
```

2020-04-23 17:22 UTC, gohabereg commented on index.ts
> +  const manager = new CronManager(process.env.REGISTRY_URL, cronManagerConfig);
Надо бы сделать проверку конфига. Как минимум на то, что есть все нужные поля, как максимум на то, что schedule соответствует cron формату

2020-04-23 17:23 UTC, nikmel2803 commented on src/manager.ts
> +    return this.channelWithRegistry.sendToQueue(
какой такой паблиш?

2020-04-28 18:03 UTC, nikmel2803 commented on index.ts
> +  const manager = new CronManager(process.env.REGISTRY_URL, cronManagerConfig);
done

2020-04-28 18:03 UTC, nikmel2803 commented on src/manager.ts
> +        await this.addTask(task.workerType, task.payload || {});
done

2020-04-28 18:03 UTC, nikmel2803 commented on src/manager.ts
> +    return this.channelWithRegistry.sendToQueue(
done

2020-04-28 18:07 UTC, neSpecc approved these changes

2020-04-28 18:07 UTC, neSpecc commented on src/types.ts
> +/**
still not fixed

2020-04-29 10:20 UTC, n0str requested changes

2020-04-29 10:20 UTC, n0str commented on README.md
> +2. Write config file according to config.sample.yml: `cp config.sample.yml config.yml`
Where is `.env` description in docs?

2020-04-29 10:20 UTC, n0str commented on docker-compose.dev.yml
> +      - .env
why do we need .env file in here? `.env` is only needed to provide variables for docker and not related to ENV environment inside containers

2020-04-29 10:20 UTC, n0str commented on docker-compose.prod.yml
> +      - ./.env:/usr/src/app/.env
is this `.env` needed for the application? I believe, we use `config.yml` in this context

2020-04-29 10:20 UTC, n0str commented on config.sample.yml
> +  - workerType: 'archiver'
isn't it cron-tasks/archiver?
Maybe we would like to have another archiver queue in Future, so it would cause name collision

2020-04-29 13:36 UTC, nikmel2803 commented on README.md
> +2. Write config file according to config.sample.yml: `cp config.sample.yml config.yml`
забыл удалить все упоминания о .env

2020-04-29 13:40 UTC, n0str approved these changes

2020-04-29 13:44 UTC, gohabereg approved these changes

2020-04-29 15:52 UTC, merged